#!/usr/bin/env python3
"""
Syncause Trace Analyzer CLI

Standalone CLI tool for analyzing Syncause SDK trace data files (.bin / .json).
Parses local trace files generated by the Syncause SDK and outputs structured
analysis results including: call chains, exceptions, data anomalies, and hints.

Usage:
    python3 analyze_trace.py <trace_file> [--issue "<issue description>"] [--format json|text]

Examples:
    python3 analyze_trace.py .syncause-cache/syncause_debug_.bin
    python3 analyze_trace.py .syncause-cache/trace.json --issue "ResolverMatch doesn't handle partial"
    python3 analyze_trace.py .syncause-cache/syncause_debug_.bin --format json
"""
from __future__ import annotations

import argparse
import json
import os
import sys

# Add the scripts directory to the path so we can import runtime_analyzer
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from runtime_analyzer import (
    CallInfo,
    ErrorInfo,
    RuntimeSnapshot,
    _parse_syncause_trace,
    extract_runtime_trace,
    extract_stdout_portion,
    parse_runtime_trace,
)


def read_trace_file(filepath: str) -> str:
    """Read trace data from a file (.bin or .json)."""
    with open(filepath, "r", errors="replace") as f:
        return f.read()


def analyze_trace_data(raw_data: str, issue_text: str = "") -> dict:
    """
    Analyze raw trace data and return structured results.

    Returns a dict with:
    - calls: list of function calls with file, line, function, args, return_value
    - errors: list of exceptions with type, message, file, line, function
    - syncause_calls: list of Syncause-specific parsed calls
    - summary: human-readable summary
    """
    results: dict = {
        "calls": [],
        "errors": [],
        "syncause_calls": [],
        "summary": [],
    }

    # Try to parse as Syncause deep call trace
    syncause_calls = _parse_syncause_trace(raw_data)
    if syncause_calls:
        results["syncause_calls"] = syncause_calls
        results["summary"].append(
            f"Parsed {len(syncause_calls)} Syncause deep call chain entries."
        )

    # Try to extract runtime trace section
    trace_text = extract_runtime_trace(raw_data)
    stdout_text = extract_stdout_portion(raw_data)

    if trace_text or stdout_text:
        snapshot = parse_runtime_trace(trace_text, stdout_text, issue_text)
        results["calls"] = [
            {
                "file": c.file,
                "line": c.line,
                "function": c.function,
                "args": c.args[:200],
                "return_value": c.return_value[:200] if c.return_value else "",
            }
            for c in snapshot.calls
        ]
        if snapshot.error:
            results["errors"].append(
                {
                    "type": snapshot.error.type,
                    "message": snapshot.error.message,
                    "file": snapshot.error.file,
                    "line": snapshot.error.line,
                    "function": snapshot.error.function,
                }
            )
        results["summary"].append(
            f"Parsed {len(snapshot.calls)} function calls, {1 if snapshot.error else 0} exceptions."
        )

    # If no structured data found, try raw JSON parsing
    if not results["calls"] and not results["syncause_calls"]:
        try:
            json_data = json.loads(raw_data)
            if isinstance(json_data, list):
                results["syncause_calls"] = json_data
                results["summary"].append(
                    f"Loaded {len(json_data)} entries from JSON trace."
                )
            elif isinstance(json_data, dict):
                # Single trace record
                results["syncause_calls"] = [json_data]
                results["summary"].append("Loaded 1 entry from JSON trace.")
        except (json.JSONDecodeError, ValueError):
            results["summary"].append(
                "Warning: Could not parse trace data in any known format."
            )

    return results


def format_text_output(results: dict) -> str:
    """Format results as human-readable text."""
    lines: list[str] = []
    lines.append("=" * 70)
    lines.append("SYNCAUSE TRACE ANALYSIS REPORT")
    lines.append("=" * 70)
    lines.append("")

    # Summary
    for s in results.get("summary", []):
        lines.append(f"  {s}")
    lines.append("")

    # Errors (most important)
    errors = results.get("errors", [])
    if errors:
        lines.append("-" * 70)
        lines.append("EXCEPTIONS DETECTED")
        lines.append("-" * 70)
        for err in errors:
            lines.append(f"  Type:     {err['type']}")
            lines.append(f"  Message:  {err['message']}")
            lines.append(f"  Location: {err['file']}:{err['line']} in {err['function']}")
            lines.append("")

    # Syncause deep call chain
    syncause_calls = results.get("syncause_calls", [])
    if syncause_calls:
        lines.append("-" * 70)
        lines.append(f"SYNCAUSE CALL CHAIN ({len(syncause_calls)} entries)")
        lines.append("-" * 70)
        for call in syncause_calls[:50]:
            depth = call.get("depth", 0)
            indent = "  " * (depth + 1)
            func = call.get("func_full", call.get("func", "?"))
            file = call.get("file", "?")
            line = call.get("line", "?")
            args = call.get("args", "")
            if len(args) > 80:
                args = args[:80] + "..."
            lines.append(f"{indent}|- {func}({args})")
            lines.append(f"{indent}   at {file}:{line}")
        if len(syncause_calls) > 50:
            lines.append(f"  ... and {len(syncause_calls) - 50} more entries")
        lines.append("")

    # Standard parsed calls
    calls = results.get("calls", [])
    if calls:
        lines.append("-" * 70)
        lines.append(f"FUNCTION CALLS ({len(calls)} entries)")
        lines.append("-" * 70)
        for call in calls[:30]:
            func = call.get("function", "?")
            file = call.get("file", "?")
            line = call.get("line", "?")
            args = call.get("args", "")
            ret = call.get("return_value", "")
            if len(args) > 60:
                args = args[:60] + "..."
            if len(ret) > 60:
                ret = ret[:60] + "..."
            lines.append(f"  {func}({args})")
            lines.append(f"    at {file}:{line}")
            if ret:
                lines.append(f"    -> {ret}")
        if len(calls) > 30:
            lines.append(f"  ... and {len(calls) - 30} more entries")
        lines.append("")

    lines.append("=" * 70)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Analyze Syncause SDK trace data files."
    )
    parser.add_argument(
        "trace_file",
        help="Path to the trace data file (.bin or .json)",
    )
    parser.add_argument(
        "--issue",
        default="",
        help="Issue description text for context-aware analysis",
    )
    parser.add_argument(
        "--format",
        choices=["json", "text"],
        default="text",
        help="Output format (default: text)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.trace_file):
        print(f"Error: File not found: {args.trace_file}", file=sys.stderr)
        sys.exit(1)

    raw_data = read_trace_file(args.trace_file)
    if not raw_data.strip():
        print(f"Error: File is empty: {args.trace_file}", file=sys.stderr)
        sys.exit(1)

    results = analyze_trace_data(raw_data, args.issue)

    if args.format == "json":
        print(json.dumps(results, indent=2, default=str))
    else:
        print(format_text_output(results))


if __name__ == "__main__":
    main()
